export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const SHOW_POSTS_REQUEST = 'SHOW_POSTS_REQUEST'
export const SHOW_POSTS_SUCCESS = 'SHOW_POSTS_SUCCESS'
export const SHOW_POSTS_FAIL = 'SHOW_POSTS_FAIL'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const SHOW_POST_REQUEST = 'SHOW_POST_REQUEST'
export const SHOW_POST_SUCCESS = 'SHOW_POST_SUCCESS'
export const SHOW_POST_FAIL = 'SHOW_POST_FAIL'
export const SHOW_POST_RESET = 'SHOW_POST_RESET'

